/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 viking_ship.glb --transform 
Files: viking_ship.glb [62.01MB] > C:\Users\Morad\react-main-projects\react-portfolio-2024\public\models\viking_ship-transformed.glb [3.57MB] (94%)
Author: Georg Klein (https://sketchfab.com/kleingeo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/viking-ship-d32f48fd2be64f948ee4d80a6da70ae8
Title: Viking Ship
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { OrbitControls } from "@react-three/drei";

export function VikingShip(props) {
  const { nodes, materials } = useGLTF("./models/viking_ship-transformed.glb");
  return (
    <group {...props} dispose={null}>
      {/* <OrbitControls /> */}
      <mesh
        geometry={nodes.ship_sail1_0.geometry}
        material={materials.sail1}
        scale={0.008}
      />
      <mesh
        geometry={nodes.ship_shields_0.geometry}
        material={materials.shields}
        scale={0.008}
      />
      <mesh
        geometry={nodes.ship_trimsheet_0.geometry}
        material={materials.trimsheet}
        scale={0.008}
      />
      <mesh
        geometry={nodes.ship_stuff_0.geometry}
        material={materials.stuff}
        scale={0.008}
      />
      <mesh
        geometry={nodes.ship_woodplanks_0.geometry}
        material={materials.woodplanks}
        scale={0.008}
      />
      <mesh
        geometry={nodes.ship_glow_0.geometry}
        material={materials.glow}
        scale={0.008}
      />
    </group>
  );
}

useGLTF.preload("./models/viking_ship-transformed.glb");
